-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Feb 10, 2024 at 09:24 PM
-- Server version: 10.6.14-MariaDB-cll-lve
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u549415590_tracer`
--

-- --------------------------------------------------------

--
-- Table structure for table `bank_alumni`
--

CREATE TABLE `bank_alumni` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `nama` varchar(255) NOT NULL,
  `nim` varchar(255) NOT NULL,
  `prodi` varchar(255) NOT NULL,
  `angkatan` varchar(255) NOT NULL,
  `kategori` varchar(255) NOT NULL,
  `alumni1` text DEFAULT NULL COMMENT 'Apakah sudah pernah mengisi formulir tracer study?*',
  `alumni2` text DEFAULT NULL COMMENT 'Tempat, tangal lahir*',
  `alumni3` text DEFAULT NULL COMMENT 'Jenis kelamin*',
  `alumni4` text DEFAULT NULL COMMENT 'No WhatsApp*',
  `alumni5` text DEFAULT NULL COMMENT 'Email*',
  `alumni6` text DEFAULT NULL COMMENT 'Alamat Lengkap*',
  `alumni7` text DEFAULT NULL COMMENT 'IPK setelah lulus*',
  `alumni8` text DEFAULT NULL COMMENT 'Tahun Masuk Kuliah di Universitas Borneo Lestari*',
  `alumni9` text DEFAULT NULL COMMENT 'Tahun Lulus (Berdasarkan Tanggal Wisuda)*',
  `alumni10` text DEFAULT NULL COMMENT 'Semester Lulus (Berdasarkan tanggal Yudisium)*',
  `alumni11` text DEFAULT NULL COMMENT 'Berapa lama anda menunggu untuk mendapatkan pekerjaan setelah lulus? (dalam satuan bulan, terhitung setelah yudisium) *Indikator masa tunggu merupakan salah satu poin penilaian akreditasi. Jika saat mengisi kuesioner ini Anda belum mendapatkan pekerjaan maka dapat menuliskan tanda "-"*',
  `alumni12` text DEFAULT NULL COMMENT 'Apakah anda bersedia untuk berbagi dengan almamater Universitas Borneo Lestari?*',
  `alumni13` text DEFAULT NULL COMMENT 'Jika bersedia, hal apa yang ingin anda bagikan untuk almamater Universitas Borneo Lestari (dapat lebih dari satu pilihan)?',
  `alumni14` text DEFAULT NULL COMMENT 'Kepuasan alumni terhadap Dosen Program Studi/Fakultas ? Aspek yang dinilai antara lain keandalan dan kemampuan dosen dalam memberikan pelayanan terhadap mahasiswa, daya tanggap dosen dalam membantu mahasiswa dan memberikan jasa dengan cepat, kepastian bahwa pelayanan dosen sesuai dengan ketentuan, dan kepedulian dosen dalam memberi perhatian kepada mahasiswa (Keterangan skala : 1 = kurang, 2 = cukup, 3 = baik, 4 = sangat baik)*',
  `alumni15` text DEFAULT NULL COMMENT '	Kepuasan alumni terhadap Tenaga Kependidikan? Aspek yang dinilai antara lain keandalan dan kemampuan tenaga kependidikan dalam memberikan pelayanan terhadap mahasiswa, daya tanggap tenaga kependidikan dalam membantu mahasiswa dan memberikan jasa dengan cepat, kepastian bahwa pelayanan tenaga kependidikan sesuai dengan ketentuan, dan kepedulian tenaga kependidikan dalam memberi perhatian kepada mahasiswa (Keterangan skala: 1 = kurang, 2 = cukup, 3 = baik, 4 = sangat baik)*',
  `alumni16` text DEFAULT NULL COMMENT '	Kepuasan alumni terhadap Pengelola Program Studi ? Aspek yang dinilai antara lain keandalan dan kemampuan pengelola program studi dalam memberikan pelayanan terhadap mahasiswa, daya tanggap pengelola program studi dalam membantu mahasiswa dan memberikan jasa dengan cepat, kepastian bahwa pelayanan pengelola program studi sesuai dengan ketentuan, dan kepedulian tenaga kependidikan dalam memberi perhatian kepada mahasiswa (Keterangan skala: 1 = kurang, 2 = cukup, 3 = baik, 4 = sangat baik)*',
  `alumni17` text DEFAULT NULL COMMENT 'Kepuasan alumni terhadap Sarana dan Prasarana Program Studi. Aspek yang dinilai antara lain kecukupan, aksesibitas, kualitas sarana dan prasarana (Keterangan skala: 1 = kurang, 2 = cukup, 3 = baik, 4 = sangat baik)*',
  `alumni18` text DEFAULT NULL COMMENT 'Kepuasan alumni terhadap Pengelolaan Keuangan selama Proses Pendidikan di Program Studi. Aspek yang dinilai adalah biaya yang dibebankan kepada alumni selama proses pendidikan dengan pelayanan yang didapatkan (Keterangan skala: 1 = kurang, 2 = cukup, 3 = baik, 4 = sangat baik)*',
  `alumni19` text DEFAULT NULL COMMENT 'Saran untuk Program Studi/Fakultas/Universitas dilingkungan Universitas Borneo Lestari*',
  `alumni20` text DEFAULT NULL,
  `belum_bekerja1` text DEFAULT NULL COMMENT 'Jika sampai saat ini anda belum bekerja*',
  `belum_bekerja2` text DEFAULT NULL COMMENT 'Faktor apa yang paling berperan dalam mendapatkan pekerjaan (dapat lebih dari satu)?*',
  `belum_bekerja3` text DEFAULT NULL COMMENT 'Jika bersedia, hal apa yang dapat anda bagikan untuk almamater Universitas Borneo Lestari (dapat lebih dari satu pilihan)?*',
  `belum_bekerja4` text DEFAULT NULL COMMENT 'Berapa perusahaan/instansi/institusi yang sudah anda lamar (lewat surat atau e-mail) sebelum anda memeroleh pekerjaan pertama ? (tulis menggunakan angka)*',
  `belum_bekerja5` text DEFAULT NULL COMMENT 'Berapa banyak perusahaan/instansi/institusi yang merespons lamaran anda ? (tulis menggunakan angka)*',
  `belum_bekerja6` text DEFAULT NULL COMMENT 'Berapa banyak perusahaan/instansi/institusi yang mengundang anda untuk wawancara? (tulis menggunakan angka)*',
  `belum_bekerja7` text DEFAULT NULL COMMENT 'Apakah anda aktif mencari pekerjaan dalam 4 minggu terakhir? Pilihlah satu jawaban*',
  `belum_bekerja8` text DEFAULT NULL,
  `belum_bekerja9` text DEFAULT NULL,
  `belum_bekerja10` text DEFAULT NULL,
  `sudah_bekerja1` text DEFAULT NULL COMMENT 'Jenis Pekerjaan/Instansi saat ini. Tuliskan Bidang perkerjaan saat ini termasuk bagian atau departemen jika bekerja pada suatu pemerintahan atau lembaga*',
  `sudah_bekerja2` text DEFAULT NULL COMMENT 'Jenis Pekerjaan saat ini*',
  `sudah_bekerja3` text DEFAULT NULL COMMENT 'Kapan anda mencari pekerjaan?*',
  `sudah_bekerja4` text DEFAULT NULL COMMENT 'Nama institusi atau jenis usaha tempat anda bekerja*',
  `sudah_bekerja5` text DEFAULT NULL COMMENT 'Jabatan pekerjaan*',
  `sudah_bekerja6` text DEFAULT NULL COMMENT 'Apa status pekerjaan anda saat ini?*',
  `sudah_bekerja7` text DEFAULT NULL COMMENT 'Lama periode pekerjaan saat ini*',
  `sudah_bekerja8` text DEFAULT NULL COMMENT 'Apakah instansi tempat Anda bekerja saat ini merupakan pekerjaan pertama anda?*',
  `sudah_bekerja9` text DEFAULT NULL COMMENT 'Nama atasan langsung Anda (beserta gelar). Tujuan pengumpulan data ini adalah untuk menghubungi atasan langsung guna mengisi tracer study untuk pengguna lulusan*',
  `sudah_bekerja10` text DEFAULT NULL COMMENT 'Alamat email atasan Anda*',
  `sudah_bekerja11` text DEFAULT NULL COMMENT 'Mohon sebutkan riwayat pekerjaan anda dan lama periodenya sebelum pekerjaan yang saat ini (jika ada). Tuliskan jenis pekerjaan dan berapa lama anda bekerja*',
  `sudah_bekerja12` text DEFAULT NULL COMMENT 'Apakah bidang pekerjaan anda relevan dengan bidang ilmu hasil pendidikan anda?*',
  `sudah_bekerja13` text DEFAULT NULL COMMENT 'Dari mana anda mendapatkan informasi pekerjaan pertama?*',
  `sudah_bekerja14` text DEFAULT NULL COMMENT 'Apakah pekerjaan anda saat ini memenuhi harapan anda (boleh memilih alasan lebih dari satu)*',
  `sudah_bekerja15` text DEFAULT NULL COMMENT 'Berapa take home pay (gaji+tunjangan+insentif+ dll) pertama anda dalam satu bulan?*',
  `sudah_bekerja16` text DEFAULT NULL COMMENT 'Faktor apa yang paling berperan dalam mendapatkan pekerjaan (dapat lebih dari satu)?*',
  `sudah_bekerja17` text DEFAULT NULL COMMENT 'Pernahkan anda pindah bekerja?*',
  `sudah_bekerja18` text DEFAULT NULL COMMENT 'Apakah alasan anda pindah bekerja?*',
  `sudah_bekerja19` text DEFAULT NULL COMMENT 'Nomor WhatsApp Pimpinan/Atasan*',
  `sudah_bekerja20` text DEFAULT NULL COMMENT 'Alamat Lengkap Tempat anda bekerja (nama jalan, kelurahan, kecamatan, kabupaten dan provinsi)*',
  `sudah_bekerja21` text DEFAULT NULL COMMENT 'Apa tingkat tempat kerja Anda ?*',
  `sudah_bekerja22` text DEFAULT NULL COMMENT 'Tingkat pendidikan apa yang paling tepat/sesuai untuk pekerjaan anda saat ini ?*',
  `sudah_bekerja23` text DEFAULT NULL,
  `sudah_bekerja24` text DEFAULT NULL,
  `sudah_bekerja25` text DEFAULT NULL,
  `berwirausaha1` text DEFAULT NULL COMMENT 'Jenis Pekerjaan/Instansi saat ini. Tuliskan Bidang perkerjaan saat ini termasuk bagian atau departemen jika bekerja pada suatu pemerintahan atau lembaga*',
  `berwirausaha2` text DEFAULT NULL COMMENT 'Jenis Pekerjaan saat ini*',
  `berwirausaha3` text DEFAULT NULL COMMENT 'Kapan anda mencari pekerjaan?*',
  `berwirausaha4` text DEFAULT NULL COMMENT 'Nama institusi atau jenis usaha tempat anda bekerja*',
  `berwirausaha5` text DEFAULT NULL COMMENT 'Jabatan pekerjaan*',
  `berwirausaha6` text DEFAULT NULL COMMENT 'Apa status pekerjaan anda saat ini?*',
  `berwirausaha7` text DEFAULT NULL COMMENT 'Lama periode pekerjaan saat ini*',
  `berwirausaha8` text DEFAULT NULL COMMENT 'Apakah instansi tempat Anda bekerja saat ini merupakan pekerjaan pertama anda?*',
  `berwirausaha9` text DEFAULT NULL COMMENT 'Nama atasan langsung Anda (beserta gelar). Tujuan pengumpulan data ini adalah untuk menghubungi atasan langsung guna mengisi tracer study untuk pengguna lulusan*',
  `berwirausaha10` text DEFAULT NULL COMMENT 'Alamat email atasan Anda*',
  `berwirausaha11` text DEFAULT NULL COMMENT 'Mohon sebutkan riwayat pekerjaan anda dan lama periodenya sebelum pekerjaan yang saat ini (jika ada). Tuliskan jenis pekerjaan dan berapa lama anda bekerja*',
  `berwirausaha12` text DEFAULT NULL COMMENT 'Apakah bidang pekerjaan anda relevan dengan bidang ilmu hasil pendidikan anda?*',
  `berwirausaha13` text DEFAULT NULL COMMENT 'Dari mana anda mendapatkan informasi pekerjaan pertama?*',
  `berwirausaha14` text DEFAULT NULL COMMENT 'Apakah pekerjaan anda saat ini memenuhi harapan anda (boleh memilih alasan lebih dari satu)*',
  `berwirausaha15` text DEFAULT NULL COMMENT 'Berapa take home pay (gaji+tunjangan+insentif+ dll) pertama anda dalam satu bulan?*',
  `berwirausaha16` text DEFAULT NULL COMMENT 'Faktor apa yang paling berperan dalam mendapatkan pekerjaan (dapat lebih dari satu)?*',
  `berwirausaha17` text DEFAULT NULL COMMENT 'Pernahkan anda pindah bekerja?*',
  `berwirausaha18` text DEFAULT NULL COMMENT 'Apakah alasan anda pindah bekerja?*',
  `berwirausaha19` text DEFAULT NULL COMMENT 'Nama usaha Anda*',
  `berwirausaha20` text DEFAULT NULL COMMENT 'Lama periode Anda berwirausaha*',
  `berwirausaha21` text DEFAULT NULL COMMENT 'Bagaimana status kepemilikan perusahaan Anda saat ini?*',
  `berwirausaha22` text DEFAULT NULL COMMENT 'Jenis usaha apakah yang Anda lakukan saat ini?*',
  `berwirausaha23` text DEFAULT NULL COMMENT 'Motivasi apa yang mendorong Anda membuka usaha mandiri?*',
  `berwirausaha24` text DEFAULT NULL COMMENT 'Apakah bidang wirausaha anda relevan dengan bidang ilmu hasil pendidikan anda (kefarmasian)?*',
  `berwirausaha25` text DEFAULT NULL COMMENT 'Berapa penghasilan pertama anda dalam satu bulan?*',
  `berwirausaha26` text DEFAULT NULL COMMENT 'Faktor apa yang paling berperan dalam berwirausaha? Jelaskan faktor yang berperan dalam anda berwirausaha*',
  `berwirausaha27` text DEFAULT NULL,
  `berwirausaha28` text DEFAULT NULL,
  `berwirausaha29` text DEFAULT NULL,
  `berwirausaha30` text DEFAULT NULL,
  `lanjut_pendidikan1` text DEFAULT NULL COMMENT 'Nama institusi*',
  `lanjut_pendidikan2` text DEFAULT NULL COMMENT 'Program studi yang diambil*',
  `lanjut_pendidikan3` text DEFAULT NULL COMMENT 'Tahun Akademik Masuk*',
  `lanjut_pendidikan4` text DEFAULT NULL COMMENT 'Semester masuk kuliah*',
  `lanjut_pendidikan5` text DEFAULT NULL COMMENT 'Nama ketua program studi/dekan*',
  `lanjut_pendidikan6` text DEFAULT NULL COMMENT 'Sumber biaya (lanjut pendidikan)*',
  `lanjut_pendidikan7` text DEFAULT NULL,
  `lanjut_pendidikan8` text DEFAULT NULL,
  `lanjut_pendidikan9` text DEFAULT NULL,
  `lanjut_pendidikan10` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `bank_alumni`
--

INSERT INTO `bank_alumni` (`id`, `nama`, `nim`, `prodi`, `angkatan`, `kategori`, `alumni1`, `alumni2`, `alumni3`, `alumni4`, `alumni5`, `alumni6`, `alumni7`, `alumni8`, `alumni9`, `alumni10`, `alumni11`, `alumni12`, `alumni13`, `alumni14`, `alumni15`, `alumni16`, `alumni17`, `alumni18`, `alumni19`, `alumni20`, `belum_bekerja1`, `belum_bekerja2`, `belum_bekerja3`, `belum_bekerja4`, `belum_bekerja5`, `belum_bekerja6`, `belum_bekerja7`, `belum_bekerja8`, `belum_bekerja9`, `belum_bekerja10`, `sudah_bekerja1`, `sudah_bekerja2`, `sudah_bekerja3`, `sudah_bekerja4`, `sudah_bekerja5`, `sudah_bekerja6`, `sudah_bekerja7`, `sudah_bekerja8`, `sudah_bekerja9`, `sudah_bekerja10`, `sudah_bekerja11`, `sudah_bekerja12`, `sudah_bekerja13`, `sudah_bekerja14`, `sudah_bekerja15`, `sudah_bekerja16`, `sudah_bekerja17`, `sudah_bekerja18`, `sudah_bekerja19`, `sudah_bekerja20`, `sudah_bekerja21`, `sudah_bekerja22`, `sudah_bekerja23`, `sudah_bekerja24`, `sudah_bekerja25`, `berwirausaha1`, `berwirausaha2`, `berwirausaha3`, `berwirausaha4`, `berwirausaha5`, `berwirausaha6`, `berwirausaha7`, `berwirausaha8`, `berwirausaha9`, `berwirausaha10`, `berwirausaha11`, `berwirausaha12`, `berwirausaha13`, `berwirausaha14`, `berwirausaha15`, `berwirausaha16`, `berwirausaha17`, `berwirausaha18`, `berwirausaha19`, `berwirausaha20`, `berwirausaha21`, `berwirausaha22`, `berwirausaha23`, `berwirausaha24`, `berwirausaha25`, `berwirausaha26`, `berwirausaha27`, `berwirausaha28`, `berwirausaha29`, `berwirausaha30`, `lanjut_pendidikan1`, `lanjut_pendidikan2`, `lanjut_pendidikan3`, `lanjut_pendidikan4`, `lanjut_pendidikan5`, `lanjut_pendidikan6`, `lanjut_pendidikan7`, `lanjut_pendidikan8`, `lanjut_pendidikan9`, `lanjut_pendidikan10`, `created_at`, `updated_at`) VALUES
(5, 'GUSTI NADYA MAULIDAWATY', 'AK122066', 'D3 TLM', '2023', 'Sudah Bekerja', 'Pertama kali mengisi', 'Banjarmasin,23 Mei 2023', 'Perempuan', '0895700729111', 'nadyaiing05@gmail.com', 'Jalan Sukarelawan No 73 Loktabat Utara, Banjarbaru', '3,59-4,00', 'Ganjil 2020/2021', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian,Kerjasama penelitian', '3', '4', '4', '3', NULL, '3', 'Semoga sarana prasarana khususnya dilaboratorium meningkat sehingga dapat menunjang pembelajaran mahasiswa selanjutnya. Semoga UNBL bisa menambah program studi baru (alih jenjang D4) untuk TLM', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Swasta (Apotek/PBF/Rumah Sakit)', 'Akademisi', 'Setelah lulus', 'Universitas Borneo Lestari', 'Laboran', 'Honorer', '3 Bulan', 'Ya', 'apt. Putri Indah Sayakti, M. Pharm. Sci', '-', '-', 'Ya', 'Program Studi Universitas Borneo Lestari', 'Ya, karena kedudukan/jabatan sesuai', 'Rp 2.000.000 – 5.000.000', 'IPK/kemampuan akademik,Asal perguruan tinggi,Pengalaman lain: kursus keterampilan', 'belum pernah', 'on', '081346881990', 'Bumi berkat jalan kelapa sawit 8 No 1 RT.2 RW.1 Banjarbaru Selatan', 'Nasional/Wiraswasta berbadan hukum', 'Tingkat yang Sama', 'Instagram @nadyaiing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(6, 'ASEP KAMARUDIN', 'SF19013', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Batulicin, 16 Juni 2001', 'Laki-laki', '085156869487', 'asepkamarudinAK@gmail.com', 'Jl. Pesantren, kel. Kampung Baru, kec. Simpang Empat, kab. Tanah Bumbu, Kal-Sel', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Ganjil', 'Ya', 'Berbagi pengalaman/keahlian,Informasi lowongan pekerjaan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Hasanuddin', 'Profesi Apoteker', '2024', 'Genap', 'Prof Dr. rer.nat. Marianti A Manggau, Apt.', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(7, 'FITRI ESNAENI', 'SF19030', 'S1 Farmasi', '2022', 'Belum Bekerja', 'Pertama kali mengisi', 'Kabupaten Grobogan 24 Agustus 2000', 'Perempuan', '081214422497', 'fesnaeni@gmail.com', 'Jl Makmur', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Genap', '-', 'Ya', 'Berbagi pengalaman/keahlian', '4', '4', '4', '4', '4', 'Tidak ada', NULL, 'Menjadi ibu rumah tangga', 'on', '0', '0', '0', 'Tidak', 'Ig: @nny.fitri22', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(8, 'NURAINI', 'DF20022', 'D3 Farmasi', '2023', 'Sudah Bekerja', 'Pertama kali mengisi', 'Bontang, 01 Juni 2002', 'Perempuan', '085247004860', 'nurnuraini0106@gmail.com', 'Jl parangtritis ex manunggal 1 bontang selatan', '3,59-4,00', 'Ganjil 2020/2021', '2023', 'Genap', 'Ya', 'Informasi lowongan pekerjaan', '3', '3', '3', '3', NULL, '3', 'Lebih baik lagi kedepannya', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Swasta (Apotek/PBF/Rumah Sakit)', 'Rumah sakit', 'Setelah lulus', 'RS LNG Badak Bontang', 'Asisten Apoteker', 'Kontrak penuh waktu', '3', 'Ya', 'apt. Rahmawati, S.Farm', 'Tidak tahu', 'Tidak ada', 'Ya', 'Relasi keluarga dan teman', 'Ya, karena gaji sesuai', 'Rp 2.000.000 – 5.000.000', 'IPK/kemampuan akademik,Kepribadian', '1 kali', 'Perbaikan gaji', '.', 'Komplek PT. Badak LNG', 'Lokal/Wilayah/Wiraswasta tidak berbadan hukum', 'Tingkat yang Sama', 'n.naaini', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(9, 'KHAIRUNNISA JOHANNA', 'SF19046', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Kandangan, 16 Juli 2001', 'Perempuan', '081211112342', 'khairunnisajohannaa@gmail.com', 'Jl. Hamran Sani Komp. Silva Karya No. 14 Rt. 008 Rw. 002, Kel/Desa Sungai Ulin, Kec. Banjarbaru Utara, Kota Banjarbaru, Kalimantan Selatan. 70714', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Pendidikan Profesi Apoteker', '2023', 'Ganjil', 'apt. Esty Restiana Rusida, M.Kes.', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(10, 'ROSYA RIZKY MAULIDYA', 'SF19170', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Banjarbaru, 11 Juni 2001', 'Perempuan', '083841981550', 'rosyarizky@gmail.com', 'Jl. A. Yani KM. 39,5 Desa. Ujung Kec. Bati-bati Kab. Tanah Laut', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Profesi Apoteker', '2023/2024', 'Genap', 'apt. Esty Restiana Rusida, M. Kes.', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(11, 'HAIRUNNISA', 'SF21212', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Batakan, 01 Agustus 2000', 'Perempuan', '‪+62 838‑6244‑7398‬', 'Hairunnisahn98@gmail.com', 'Jl sarigading banua budi rt 3 rw 2 seberang langgar nurul yakin rumah beton warna oren, KAB. HULU SUNGAI TENGAH, BARABAI, KALIMANTAN SELATAN, ID, 71315', '3,59-4,00', 'Genap 2021/2022', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Apoteker', '2023/2024', 'Genap', 'Apt. Esty Restiana Rusida, M.Kes', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(12, 'DWI NOVITA SARI', 'SF21274', 'S1 Farmasi', '2022', 'Belum Bekerja', 'Pertama kali mengisi', 'Sampit, 23 November 1998', 'Perempuan', '082157279764', 'dwinovitasari.23nov@gmail.com', 'jl bukit raya 3 no 53', '3,00-3,59', 'Ganjil 2021/2022', '2023', 'Genap', '-', 'Ya', 'on', '3', '3', '2', '3', '2', 'Lebih ditingkatkan kualitas belajar antar dosen dan mahasiswa', NULL, 'on', 'IPK/kemampuan akademik,Pengalaman lain: kursus keterampilan', '0', '0', '0', 'Tidak', 'dwnovitaaa_', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(13, 'NOOR HAYATI', 'SF19078', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Banjarmasin,27 Agustus 2000', 'Perempuan', '085753063810', 'noorhayati.0614@gmail.com', 'Jl. Samudera beruntung jaya', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian,Informasi lowongan pekerjaan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'S1 Farmasi', '2019', 'Ganjil', 'Apt. Eka Fitri Susiani, M. Farm', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(14, 'MUAWAMAH', 'SF21260', 'S1 Farmasi', '2022', 'Belum Bekerja', 'Pertama kali mengisi', '16 juli 1999', 'Perempuan', '085251619816', 'wamah1234@gmail.com', 'Desa Nelayan, Alabio Kab.HSU Kec.Sungai Tabukan KALSEL', '3,59-4,00', 'Ganjil 2021/2022', '2023', 'Genap', '-', 'Ya', 'Berbagi pengalaman/keahlian', '3', '3', '3', '3', '3', '.', NULL, 'Belum ada lowongan kerja yang sesuai dengan minat saya (karir, gaji, dll)', 'IPK/kemampuan akademik,Pengalaman lain: kursus keterampilan', '0', '0', '0', 'Tidak', 'Muawwamah_', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(15, 'NOOR HAYATI', 'SF19078', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Banjarmasin, 27 Agustus 2000', 'Perempuan', '085753063810', 'noorhayati.0614@gmail.com', 'Jl. Samudera beruntung jaya', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian,Informasi lowongan pekerjaan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Program studi Apoteker', '2024', 'Ganjil', 'Apt. Syahrizal Ramadhani, M.Clin,Pharm', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(16, 'ERSA SETIANA PUTRI', 'SF19133', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Palangka Raya, 4 Desember 2001', 'Perempuan', '081318996142', 'ersasetiana.p@gmail.com', 'Jl. Bumi Berkat 7', '3,00-3,59', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Informasi lowongan pekerjaan,Sarana dan prasarana pengembangan kampus', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Pendidikan Profesi Apoteker', '2023', 'Ganjil', 'Apt. Syahrizal Ramadhani, M.Clin, Pharm', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(17, 'NABILA SAPUTRI', 'SF19151', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Kandanngan, 22 januari 2002', 'Perempuan', '085387798129', 'Nabilasaputry2201@gmail.com', 'Komp. Permata hijau kavling A no. 08', '3,00-3,59', 'Ganjil 2023/2024', '2023', 'Ganjil', 'Ya', 'Sarana dan prasarana pengembangan kampus', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas borneo lestar', 'Pendidikan profesi apoteker', '2024', 'Genap', 'Apt. Syahrizal Ramadhani, M. Clin,Pharm.', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(18, 'JAHRATUN NISA', 'SF19042', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Tapin, 06 Januari 2001', 'Perempuan', '081256664958', 'nszahratun625@gmail.com', 'Jl.grilya rt20/03 kelurahan rantau kanan kecamatan Tapin Utara', '3,00-3,59', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Program studi pendidikan profesi apoteker', '23/24', 'Genap', 'apt. Esty Restiana Rusida, M.Kes', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(19, 'DIAH DESY FITRIATIN', 'SF19022', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Lamongan, 21 Februari 2001', 'Perempuan', '‪+62857‑5001‑7655‬', 'diahdesyf21@gmail.com', 'Jl. A Yani KM. 24. 500', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Program Studi Pendidikan Profesi Apoteker', '2023/2024', 'Genap', 'apt. Esty Restiana Rusida, M.Kes.', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(20, 'RAHMAYANTI', 'SF21234', 'S1 Farmasi', '2022', 'Sudah Bekerja', 'Pertama kali mengisi', 'Bangkuang, 31 Maret 1986', 'Perempuan', '082157865557', 'anthyluv86@gmail.com', 'Jl. Ampah- Buntok Gg. Al amin RT. 8 Asak Desa Putai Kec. Dusun Tengah Kab. Barito Timur Kalimantan Tengah', '3,59-4,00', 'Ganjil 2021/2022', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian,Informasi lowongan pekerjaan,Kerjasama penelitian,Fasilitasi tempat bekerja', '4', '4', '4', '4', NULL, '3', 'semakin lebih baik lagi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Pemerintah', 'on', 'Sebelum lulus', 'UPTD Puskesmas Ampah', 'Asisten Apoteker', 'Tenaga tetap', '19 tahun', 'Ya', 'Nelwan Adrius, S. Kep, Ns', '-', '-', 'Ya', 'Relasi keluarga dan teman', 'Ya, karena kedudukan/jabatan sesuai', 'Rp 2.000.000 – 5.000.000', 'IPK/kemampuan akademik,Kepribadian,Pengalaman lain: kursus keterampilan', 'belum pernah', 'on', '081326631375', 'Jl. veteran no. 3 Ampah kota Kec. DusunTengah kab. BaritoTimur kalimntan Tengah', 'Nasional/Wiraswasta berbadan hukum', 'Tingkat yang Sama', '-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(21, 'FITRIA NURHASNA', 'SF19032', 'S1 Farmasi', '2022', 'Belum Bekerja', 'Pertama kali mengisi', 'Muara Teweh, 27 Desember 2000', 'Perempuan', '082149571183', '082149571183', 'Jl. Jeruk komp. Berkat Nadia Permai Blok A', '3,00-3,59', 'Ganjil 2019/2020', '2023', 'Genap', '-', 'Ya', 'Berbagi pengalaman/keahlian,Sarana dan prasarana pengembangan kampus', '3', '3', '3', '3', '3', '-', NULL, 'on', 'IPK/kemampuan akademik,Ekstra kurikuler: pengalaman organisasi, kelompok studi', '-', '-', '-', 'on', 'Insagram : fitriaanrhsn', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(22, 'AKHMAD JUNAIDI', 'SF21254', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Banua Kupang, 28 Maret 2000', 'Laki-laki', '087814893768', 'junaidiakhmad000@gmail.com', 'Jl. Wanna Bakti. Ratu Elok, Banjarbaru', '3,00-3,59', 'Ganjil 2022/2023', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PSPPA Universitas Borneo Lestari', 'PSPPA', '2023/2034', 'Ganjil', 'apt. Syahrizal Ramadhani. M. Clin. Pharm.', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(23, 'ANNISA AULIA RIZKIKA', 'SF19118', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Paringin, 3 Agustus 2001', 'Perempuan', '082112452934', 'annisaauliarizkika3237@gmail.com', 'Desa layap No 73, RT 003, RW 000, Kec. Paringin, Kab. Balangan', '3,00-3,59', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Pendidikan Profesi Apoteker', '2023/2024', 'Genap', 'apt. Esty Restiana Rusida, M. Kes.', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(24, 'BAIQ NURDIANA ULFA', 'DF20003', 'D3 Farmasi', '2023', 'Sudah Bekerja', 'Pertama kali mengisi', 'Kotabaru, 03 Mei 1997', 'Perempuan', '081254064899', 'baiqnurdiana.ulfa@gmail.com', 'Desa Biduri Bersujud RT 01 RW 01, Kel. Biduri Bersujud Kec. Sungai Loban Kab. Tanah Bumbu', '3,59-4,00', 'Ganjil 2020/2021', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian,Informasi lowongan pekerjaan,Fasilitasi tempat bekerja', '4', '4', '4', '4', NULL, '4', 'Melakukan Penyuluhan dari kampus untuk siswa SMA/SMK di Tanah Bumbu, Terutama di Kecamatan Sungai Loban.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'on', 'Apotek', 'Sebelum lulus', 'Klinik Permata Bunda', 'Tenaga Teknis Kefarmasian', 'Kontrak penuh waktu', '+- 4 bulan', 'Tidak', 'atp. Muammar Fahlupi, S.Farm', 'fahlupim@yahoo.co.id', 'Bekerja di Klinik Permata Bunda kurang lebih 4 tahun', 'Ya', 'Relasi keluarga dan teman', 'Ya, karena gaji sesuai,Ya, karena kedudukan/jabatan sesuai,Ya, karena iklim kerja menyenangkan', 'Rp 2.000.000 – 5.000.000', 'IPK/kemampuan akademik,Kepribadian', '> 2 kali', 'Manajemen instansi/Lembaga perusahaan', '0852-4042-8771', 'Jl. Provinsi Sebamban 1 Blok C RT.02/RW.01 Kec. Sungai Loban Kab. Tanah Bumbu', 'Nasional/Wiraswasta berbadan hukum', 'Tingkat yang Sama', 'Instagram = baiqnurdiana', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(25, 'ANNISA MUMTAZA', 'SF19119', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Babirik, 02 Mei 2001', 'Perempuan', '08568940492', 'annisa.mumtaza02501@gmail.com', 'Jl. Barito gg.VI no.24, kab. Kapuas. Kalimantan tengah', '3,00-3,59', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian,Informasi lowongan pekerjaan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Profesi pendidikan apoteker', '2024', 'Ganjil', 'apt. Esty Restiana Rusida, M.Kes.', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(26, 'CINDY RORA RIZKY', 'SF19018', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'kotabaru, 29 Januari 2001', 'Perempuan', '082253858437', 'crorrra2929@gmail.com', 'Jl.karya utama Gg rahmat Kotabaru pulau laut utara', '3,00-3,59', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Apoteker', '2024', 'Ganjil', 'Apt. Esty Restiana Rusida, M.Kes', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(27, 'DHAIFINA SALSABILA', 'SF19127', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'rantau,4 juli 2001', 'Perempuan', '082152994017', 'dhaifinasalsabila04@gmail.com', 'Jl.A.Yani No.08 Rt.05 Rica Paringin Kota Kabupaten Balangan Kalimantan Selatan', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Ganjil', 'Ya', 'Berbagi pengalaman/keahlian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'universitas borneo lestari', 'program studi pendidikan profesi apoteker', '2023/2024', 'Ganjil', 'Apt. Esty Restiana Rusida, M.Kes', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(28, 'FITRI', 'SF19029', 'S1 Farmasi', '2022', 'Sudah Bekerja', 'Pertama kali mengisi', 'Kapuas, 23 Desember 2001', 'Perempuan', '085163231220', 'xztfitri@gmail.com', 'Jl. Dukuh Jaya I, Sungai Besar Banjarbaru', '3,00-3,59', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Informasi lowongan pekerjaan', '4', '4', '4', '4', NULL, '4', 'lebih ditingkatkan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Swasta (Apotek/PBF/Rumah Sakit)', 'Apotek', 'Sebelum lulus', 'Apotek Bima', 'TTK', 'Kontrak penuh waktu', '5 bulan', 'Ya', 'apt. Ina, S.Farm', 'bimaapotek@gmail.com', 'tidak ada', 'Ya', 'Iklan/media massa', 'Ya, karena kedudukan/jabatan sesuai', 'Kurang dari Rp 2.000.000', 'Kepribadian,Pengalaman lain: kursus keterampilan', 'belum pernah', 'on', '+62 895-3757-97500', 'Jl. karang rejo', 'Lokal/Wilayah/Wiraswasta tidak berbadan hukum', 'Tingkat yang Sama', 'desfleurss_', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(29, 'LISTIYA NOR HIDAYATI', 'SF19141', 'S1 Farmasi', '2022', 'Lanjut Pendidikan', 'Pertama kali mengisi', 'Banjarmasin, 25 September 2001', 'Perempuan', '089635784633', 'listia.hidayati18@gmail.com', 'Jl. Manggis Gg. Janar Putih, RT 013, RW 001, Banjarmasin Timur, Kota Banjarmasin', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Universitas Borneo Lestari', 'Pendidikan Profesi Apoteker', '2024/2025', 'Genap', 'Apt. Syahrizal Ramadhani, M.Clin,Pharm', 'Mandiri', NULL, NULL, NULL, NULL, NULL, NULL),
(30, 'MUHAMMAD RIZHA HARIESI', 'SF19146', 'S1 Farmasi', '2023', 'Berwirausaha', 'Pertama kali mengisi', 'Amuntai, 27 Mei 2001', 'Laki-laki', '087734217391', 'Izahariesi@gmail.com', 'Jl. Bihmanvilla No.112 Rt.07 Amuntai tengah', '3,00-3,59', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', '4', '3', '3', '3', NULL, '3', 'Lebih dikembangkan lagi dari sisi minat bakat mahasiswa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Setelah lulus', 'Perdagangan Sarang Walet', 'Penilik Usaha', 'Tidak', 'Saya Sendiri', 'Izahariesi@gmail.com', 'Kurang lebih 1 tahun', 'Tidak', 'on', 'Ya, karena gaji sesuai', 'Rp 10.000.000 – 15.000.000', 'Kepribadian,Pengalaman lain: kursus keterampilan', '1 kali', 'Peluang karir', 'Perdagangan Walet', '2 tahun', 'on', 'Dagang', 'Mencari tantangan', 'Tidak', 'Rp 5.000.000 – 10.000.000', 'Faktor Keluarga', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(31, 'NOOR HIKMAH', 'SF19079', 'S1 Farmasi', '2022', 'Sudah Bekerja', 'Pertama kali mengisi', 'Banjarmasin, 06 April 2001', 'Perempuan', '081254660761', 'nnurhikmahhf@gmail.com', 'Jln mistar cokrokusumo', '3,00-3,59', 'Ganjil 2018/2019', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', '3', '3', '3', '3', NULL, '2', 'Semoga bisa lebih maju dan berkembang lagi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Lembaga Non Profit', 'on', 'Setelah lulus', 'FIF', 'CS', 'Kontrak penuh waktu', '1 tahun', 'Tidak', 'Kurdi, SHI', 'kurdi_fifgroup.astra@yahoo.co.id', 'Jaga toko masker dan peralatan kesehat keacare selama 1 bulan', 'Tidak', 'Relasi keluarga dan teman', 'Ya, karena gaji sesuai', 'Rp 2.000.000 – 5.000.000', NULL, 'belum pernah', 'Peluang karir', '+62 852-4871-3734', 'Jln A yani km 37 batas kota martapura disamping mixue batas kota', 'Lokal/Wilayah/Wiraswasta tidak berbadan hukum', 'Tingkat yang Sama', 'nnurhikmahh', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(32, 'HELMA YANTI', 'SF19037', 'S1 Farmasi', '2022', 'Belum Bekerja', 'Pertama kali mengisi', 'Negara, 22 Juli 2001', 'Perempuan', '081528476392', 'helmayantiixc@gmail.com', 'Jl. Sungai Garuda, Rt.4, Rw.2, Desa Sungai Garuda, Kecamatan Daha Utara, Kabupaten Hulu Sungai Selatan, Provisi Kalimantan Selatan, Indonesia, Kode Pos : 71253', '2,00-2,59', 'Ganjil 2019/2020', '2023', 'Genap', '-', 'Ya', 'Berbagi pengalaman/keahlian,Kerjasama penelitian', '3', '3', '3', '3', '2', '.', NULL, 'TRTTK belum keluar', 'Pengalaman lain: kursus keterampilan', '2', '2', '1', 'Tidak', '-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(33, 'ADI SAPUTRA', 'SF19003', 'S1 Farmasi', '2022', 'Sudah Bekerja', 'Pertama kali mengisi', 'banjarmasin 24 mei 2001', 'Laki-laki', '085175240544', 'adisptr24@gmail.com', 'jl kuin selatan gg rahmah', '3,59-4,00', 'Ganjil 2019/2020', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian', '4', '4', '4', '4', NULL, '4', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Swasta (Apotek/PBF/Rumah Sakit)', 'PBF', 'Setelah lulus', 'Dexa medica', 'medical representative', 'Kontrak penuh waktu', '2 bulan', 'Tidak', 'anton hari utomo', NULL, 'wirausahs', 'Ya', 'Relasi keluarga dan teman', 'Ya, karena gaji sesuai', 'Rp 5.000.000 – 10.000.000', 'Kepribadian', '1 kali', 'Kesesuaian dengan bidang ilmu', NULL, NULL, 'Multinasional/Internasional', 'Tingkat yang Sama', 'adi.sptra', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(34, 'MIR’ATUL KAMILAH', 'SF19055', 'S1 Farmasi', '2022', 'Belum Bekerja', 'Pertama kali mengisi', 'Tanah Laut, 22 Mei 2001', 'Perempuan', '081349075056', 'Miratul.kamilah.7@gmail.com', 'Jl.A.Yani Rt.012 Rw.004, Desa Jorong, Kab.Tanah Laut', '3,00-3,59', 'Ganjil 2019/2020', '2023', 'Genap', '-', 'Ya', 'Berbagi pengalaman/keahlian', '4', '4', '4', '2', '2', 'Lebih cepat dan tepat waktu', NULL, 'Sudah melamar tapi tidak dipanggil', 'IPK/kemampuan akademik,on', '5', '2', '1', 'Ya, tapi saya belum pasti akan bekerja dalam 2 minggu ke depan', 'Ig : Mirakamilah_', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(35, 'KHAIRUN NIDA LESTARI', 'DF20030', 'D3 Farmasi', '2023', 'Sudah Bekerja', 'Pertama kali mengisi', 'Handil Purai, 01 Januari 2002', 'Perempuan', '085348194559', 'khairunnidalestari@gmail.com', 'Komplek Buana Permai Blok B No. 16 kelurahan Guntung Paikat, Banjarbaru Selatan', '3,59-4,00', 'Ganjil 2020/2021', '2023', 'Genap', 'Ya', 'Berbagi pengalaman/keahlian,Informasi lowongan pekerjaan', '4', '4', '4', '4', NULL, '4', 'Semoga kedepannya lebih baik lagi  dan lulusan dari universitas Borneo Lestari di siapkan lebih matang untuk menghadapi dunia kerja.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Swasta (Apotek/PBF/Rumah Sakit)', 'Rumah sakit', 'Sebelum lulus', 'RSI Sultan Agung Banjarbaru', 'Tenaga Teknisi Kefarmasian', 'Kontrak penuh waktu', '1 Bulan', 'Tidak', 'Apt. Alfira Aryanti, S. Farm', '-', 'Apotek Keacare', 'Ya', 'Program Studi Universitas Borneo Lestari', 'Ya, karena gaji sesuai', 'Kurang dari Rp 2.000.000', 'IPK/kemampuan akademik,Kepribadian,Ekstra kurikuler: pengalaman organisasi, kelompok studi', '1 kali', 'Perbaikan gaji', '-', 'Komplek Kota Citra Graha, Jl. A. Yani No.Km. 17,5, RT.015/RW.003, Kelurahan Landasan Ulin Barat, Kec. Liang Anggang, Kota Banjar Baru, Kalimantan Selatan 70722', 'Lokal/Wilayah/Wiraswasta tidak berbadan hukum', 'Tingkat yang Sama', 'nidalestari_', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `bank_alumni`
--
ALTER TABLE `bank_alumni`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `bank_alumni`
--
ALTER TABLE `bank_alumni`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
